import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'hu' | 'en' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  hu: {
    'nav.home': 'Főoldal',
    'nav.about': 'Rólunk',
    'nav.programs': 'Oktatás',
    'nav.news': 'Hírek',
    'nav.media': 'Média',
    'nav.participation': 'Részvétel',
    'nav.contact': 'Kapcsolat',
    'hero.title': 'Magyar Iskola Tokió',
    'hero.subtitle': 'Hagyomány, Közösség, Jövő',
    'hero.cta': 'Csatlakozz hozzánk',
    'about.title': 'Iskolánkról',
    'about.mission': 'Küldetésünk',
    'about.desc': 'A Magyar Iskola Tokió célja a magyar nyelv és kultúra ápolása Japánban élő gyermekek számára.',
    'programs.title': 'Oktatás',
    'programs.desc': 'Havonta kétszer, szombatonként tartunk foglalkozásokat.',
    'programs.creative.title': 'Kiscsoport (1-5 éves korosztály)',
    'programs.creative.desc': 'Dalok és mondókák a legkisebbek részére. Babák, bölcsisek és ovisok csoportja.',
    'programs.language.title': 'Középső csoport (6-9 évesek)',
    'programs.language.desc': 'Olvasás és írás elsajátítása, játékos magyar nyelvtanulás az alsó tagozatos korú gyermekek számára.',
    'programs.community.title': 'Nagycsoport (10 éves kortól)',
    'programs.community.desc': 'Szókincsfejlesztés, helyesírási gyakorlatok nagyobb gyermekek számára',
    'news.title': 'Híreink',
    'news.desc': 'Aktuális információk és események iskolánk életéből.',
    'news.video.tag': 'Videó Interjú',
    'news.video.title': 'Beszélgetés Nagyváthy Viktóriával',
    'news.video.desc': 'Tekintsétek meg a legújabb videóinterjút iskolánk vezetőjével, ahol mesél a kezdetekről és a mindennapokról.',
    'news.fbvideo.tag': 'Facebook Videó',
    'news.fbvideo.title': 'Bemutatkozó Interjú',
    'news.fbvideo.desc': 'Nézzétek meg az iskola első videós bemutatkozását, melyet Máté Zita készített Nagyváthy Viktóriával.',
    'news.article1.date': '2025. Augusztus 05.',
    'news.article1.title': 'Interjú Nagyváthy Viktóriával',
    'news.article1.desc': 'Olvassátok el a Marie Claire interjúját iskolánk vezetőjével az alapításról és a jövőbeli tervekről.',
    'news.readMore': 'Tovább olvasom',
    'news.article2.date': '2025. Szeptember',
    'news.article2.title': 'Új tanév indul!',
    'news.article2.desc': 'Szeretettel várunk minden régi és új diákot a szeptemberben induló foglalkozásainkra. Jelentkezni emailben lehet.',
    'news.contactUs': 'Kapcsolatfelvétel',
    'media.title': 'Média',
    'media.desc': 'Iskolánk megjelenése a médiában és videós interjúk.',
    'contact.title': 'Lépj kapcsolatba velünk',
    'contact.desc': 'Szeretettel várunk megkeresésedre!',
    'contact.location': 'Helyszín',
    'contact.address': 'Helyszín',
    'contact.institute': 'Liszt Intézet Magyar Kulturális Központ Tokió',
    'contact.email': 'Email címünk',
    'contact.form.name': 'Név',
    'contact.form.email': 'E-mail',
    'contact.form.message': 'Üzenet',
    'contact.form.send': 'Küldés',
    'participation.title': 'Részvétel',
    'participation.desc': 'Csatlakozz a Magyar Iskola Tokióhoz!',
    'participation.welcome': 'Kiket várunk?',
    'participation.welcome.desc': 'Magyar, illetve magyar származású gyermekeket várunk az alábbi korcsoportokba:',
    'participation.group1.title': 'Kiscsoport',
    'participation.group1.age': '0-5 éves korig',
    'participation.group1.desc': 'Dalok, mondókák és játékok a legkisebbek számára.',
    'participation.group2.title': 'Középső csoport',
    'participation.group2.age': '6-9 évesek',
    'participation.group2.desc': 'Olvasás, írás és játékos magyar nyelvtanulás.',
    'participation.group3.title': 'Nagycsoport',
    'participation.group3.age': '10 éves kortól',
    'participation.group3.desc': 'Szókincsfejlesztés és helyesírási gyakorlatok.',
    'participation.membership': 'Tagdíj',
    'participation.membership.desc': 'Az éves tagdíj: XY yen',
    'participation.apply': 'Jelentkezés',
    'participation.apply.desc': 'Kérjük, töltsd ki a jelentkezési űrlapot az alábbi gombra kattintva.',
    'participation.applyButton': 'Jelentkezési Űrlap',
    'footer.rights': 'Minden jog fenntartva.',
    'footer.creator': 'Készítette: Nishizawa Gabriella Szilvia',
    'form.title': 'Jelentkezési Lap',
    'form.desc': 'Kérjük, töltse ki az alábbi űrlapot a jelentkezéshez.',
    'form.childName': 'Gyermek neve',
    'form.birthDate': 'Születési dátum',
    'form.parentName': 'Szülő neve',
    'form.email': 'Email cím',
    'form.phone': 'Telefonszám',
    'form.message': 'Egyéb megjegyzés',
    'form.submit': 'Jelentkezés elküldése',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.programs': 'Programs',
    'nav.news': 'News',
    'nav.media': 'Media',
    'nav.participation': 'Participation',
    'nav.contact': 'Contact',
    'hero.title': 'Hungarian School Tokyo',
    'hero.subtitle': 'Tradition, Community, Future',
    'hero.cta': 'Join Us',
    'about.title': 'About Our School',
    'about.mission': 'Our Mission',
    'about.desc': 'The Hungarian School Tokyo aims to nurture Hungarian language and culture for children living in Japan.',
    'programs.title': 'Activities',
    'programs.desc': 'We hold classes twice a month on Saturdays.',
    'programs.creative.title': 'Creative Workshops',
    'programs.creative.desc': 'Arts and crafts with Hungarian motifs.',
    'programs.language.title': 'Language Education',
    'programs.language.desc': 'Playful Hungarian language learning for all levels.',
    'programs.community.title': 'Community Events',
    'programs.community.desc': 'Holidays, camps, and excursions for families.',
    'news.title': 'Latest News',
    'news.desc': 'Current information and events from our school life.',
    'news.video.tag': 'Video Interview',
    'news.video.title': 'Conversation with Viktória Nagyváthy',
    'news.video.desc': 'Watch the latest video interview with the head of our school, talking about the beginnings and daily life.',
    'news.fbvideo.tag': 'Facebook Video',
    'news.fbvideo.title': 'Introductory Interview',
    'news.fbvideo.desc': 'Watch the school\'s first video introduction, an interview with Viktória Nagyváthy by Zita Máté.',
    'news.article1.date': 'August 05, 2025',
    'news.article1.title': 'Interview with Viktória Nagyváthy',
    'news.article1.desc': 'Read the Marie Claire interview with our school leader about the foundation and future plans.',
    'news.readMore': 'Read More',
    'news.article2.date': 'September 2025',
    'news.article2.title': 'New School Year Starts!',
    'news.article2.desc': 'We welcome all old and new students to our classes starting in September. You can apply via email.',
    'news.contactUs': 'Contact Us',
    'media.title': 'Media',
    'media.desc': 'Our school in the media and video interviews.',
    'contact.title': 'Contact Us',
    'contact.desc': 'We look forward to hearing from you!',
    'contact.location': 'Location',
    'contact.address': 'Location',
    'contact.institute': 'Liszt Institute Hungarian Cultural Center Tokyo',
    'contact.email': 'Our Email',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send',
    'participation.title': 'Participation',
    'participation.desc': 'Join the Hungarian School Tokyo!',
    'participation.welcome': 'Who are we looking for?',
    'participation.welcome.desc': 'We welcome Hungarian and Hungarian-heritage children in the following age groups:',
    'participation.group1.title': 'Young Group',
    'participation.group1.age': 'Up to 5 years old',
    'participation.group1.desc': 'Songs, rhymes and games for the youngest.',
    'participation.group2.title': 'Middle Group',
    'participation.group2.age': '6-9 years old',
    'participation.group2.desc': 'Reading, writing and playful Hungarian language learning.',
    'participation.group3.title': 'Older Group',
    'participation.group3.age': '10 years and up',
    'participation.group3.desc': 'Vocabulary development and spelling practice.',
    'participation.membership': 'Membership Fee',
    'participation.membership.desc': 'Annual membership fee: XY yen',
    'participation.apply': 'Application',
    'participation.apply.desc': 'Please fill out the application form by clicking the button below.',
    'participation.applyButton': 'Application Form',
    'footer.rights': 'All rights reserved.',
    'footer.creator': 'Created by Gabriella Szilvia Nishizawa',
    'form.title': 'Application Form',
    'form.desc': 'Please fill out the form below to apply.',
    'form.childName': 'Child\'s Name',
    'form.birthDate': 'Date of Birth',
    'form.parentName': 'Parent\'s Name',
    'form.email': 'Email Address',
    'form.phone': 'Phone Number',
    'form.message': 'Other Comments',
    'form.submit': 'Send Application',
  },
  jp: {
    'nav.home': 'ホーム',
    'nav.about': '私たちについて',
    'nav.programs': 'プログラム',
    'nav.news': 'ニュース',
    'nav.media': 'メディア',
    'nav.participation': '参加',
    'nav.contact': 'お問い合わせ',
    'hero.title': '東京ハンガリー学校',
    'hero.subtitle': '伝統、コミュニティ、未来',
    'hero.cta': '参加する',
    'about.title': '学校紹介',
    'about.mission': '私たちの使命',
    'about.desc': '東京ハンガリー学校は、日本に住む子供たちのためにハンガリー語と文化を育むことを目的としています。',
    'programs.title': '活動内容',
    'programs.desc': '月に2回、土曜日に授業を行っています。',
    'programs.creative.title': 'クリエイティブ・ワークショップ',
    'programs.creative.desc': 'ハンガリーのモチーフを使った芸術と工芸。',
    'programs.language.title': '語学教育',
    'programs.language.desc': 'あらゆるレベルに対応した遊び心のあるハンガリー語学習。',
    'programs.community.title': 'コミュニティイベント',
    'programs.community.desc': '家族向けの祝日行事、キャンプ、遠足。',
    'news.title': 'ニュース',
    'news.desc': '学校生活からの最新情報とイベント。',
    'news.video.tag': 'ビデオインタビュー',
    'news.video.title': 'ナジヴァーティ・ヴィクトリアとの対談',
    'news.video.desc': '学校代表への最新ビデオインタビューをご覧ください。設立の経緯や日々の活動について語っています。',
    'news.fbvideo.tag': 'Facebookビデオ',
    'news.fbvideo.title': '紹介インタビュー',
    'news.fbvideo.desc': 'マーテー・ジタによるナジヴァーティ・ヴィクトリアへのインタビュー、学校初の紹介ビデオをご覧ください。',
    'news.article1.date': '2025年8月5日',
    'news.article1.title': 'ナジヴァーティ・ヴィクトリア インタビュー',
    'news.article1.desc': '設立と今後の計画について、学校代表へのMarie Claire誌のインタビューをお読みください。',
    'news.readMore': '続きを読む',
    'news.article2.date': '2025年9月',
    'news.article2.title': '新学期が始まります！',
    'news.article2.desc': '9月から始まるクラスに、新旧すべての生徒を歓迎します。メールでお申し込みいただけます。',
    'news.contactUs': 'お問い合わせ',
    'media.title': 'メディア',
    'media.desc': 'メディアに掲載された学校と動画インタビュー。',
    'contact.title': 'お問い合わせ',
    'contact.desc': 'ご連絡をお待ちしております！',
    'contact.location': '場所',
    'contact.address': '場所',
    'contact.institute': 'リスト・ハンガリー文化センター東京',
    'contact.email': 'メールアドレス',
    'contact.form.name': '名前',
    'contact.form.email': 'メール',
    'contact.form.message': 'メッセージ',
    'contact.form.send': '送信',
    'participation.title': '参加',
    'participation.desc': '東京ハンガリー学校に参加しましょう！',
    'participation.welcome': 'どんなお子様をお待ちしていますか？',
    'participation.welcome.desc': 'ハンガリー系またはハンガリー系の子どもたちを以下の年齢グループでお待ちしています：',
    'participation.group1.title': '小さいグループ',
    'participation.group1.age': '5歳まで',
    'participation.group1.desc': '最年少のための歌、童謡、ゲーム。',
    'participation.group2.title': '中グループ',
    'participation.group2.age': '6～9歳',
    'participation.group2.desc': '読み書きと楽しいハンガリー語学習。',
    'participation.group3.title': '大きいグループ',
    'participation.group3.age': '10歳以上',
    'participation.group3.desc': '語彙開発とスペリング練習。',
    'participation.membership': '会費',
    'participation.membership.desc': '年間会費：XY円',
    'participation.apply': '申し込み',
    'participation.apply.desc': '下のボタンをクリックして申し込みフォームにご記入ください。',
    'participation.applyButton': '申し込みフォーム',
    'footer.rights': 'All rights reserved.',
    'footer.creator': '作成者: 西澤 ガブリエッラ シルビア',
    'form.title': '申込書',
    'form.desc': '申し込みには以下のフォームに記入してください。',
    'form.childName': 'お子様の名前',
    'form.birthDate': '生年月日',
    'form.parentName': '保護者の名前',
    'form.email': 'メールアドレス',
    'form.phone': '電話番号',
    'form.message': 'その他コメント',
    'form.submit': '申し込みを送信',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('hu');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if
